name: cabme
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.1
  google_sign_in: ^6.2.2
  clipboard: ^0.1.3
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  dotted_border: ^2.1.0
  easy_autocomplete: ^1.6.0
  firebase_app_check: ^0.3.1+5
  firebase_auth: ^5.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.4
  flutter_easyloading: ^3.0.5
  flutter_html: any
  flutter_local_notifications: ^17.2.3
  flutter_osm_plugin: ^1.3.5
  flutter_paypal_native: ^2.1.0
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^11.2.0
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: any
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  google_maps_place_picker_mb: ^3.1.2
  googleapis_auth: ^1.6.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  location: ^7.0.1
  map_launcher: ^3.5.0
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  pinput: ^5.0.0
  razorpay_flutter: ^1.3.7
  share_plus: ^10.1.0
  shared_preferences: ^2.3.2
  text_scroll: ^0.2.0
  url_launcher: ^6.3.1
  video_compress: ^3.1.3
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3
  xendit_flutter: ^0.0.1
  provider: ^6.1.2
  flutter_google_places_hoc081098: ^2.0.0
  in_app_review: ^2.0.9

dependency_overrides:
  webview_flutter: ^4.10.0
  http: ^1.2.2
  uuid: ^4.5.1
  google_api_headers: ^4.2.4
  js: ^0.7.1
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Switzer-Black
      fonts:
        - asset: assets/fonts/Switzer-Black.otf

    - family: Switzer-Bold
      fonts:
        - asset: assets/fonts/Switzer-Bold.otf

    - family: Switzer-Extrabold
      fonts:
        - asset: assets/fonts/Switzer-Extrabold.otf

    - family: Switzer-Extralight
      fonts:
        - asset: assets/fonts/Switzer-Extralight.otf

    - family: Switzer-Italic
      fonts:
        - asset: assets/fonts/Switzer-Italic.otf

    - family: Switzer-Medium
      fonts:
        - asset: assets/fonts/Switzer-Medium.otf

    - family: Switzer-Regular
      fonts:
        - asset: assets/fonts/Switzer-Regular.otf

    - family: Switzer-Semibold
      fonts:
        - asset: assets/fonts/Switzer-Semibold.otf

    - family: Switzer-Thin
      fonts:
        - asset: assets/fonts/Switzer-Thin.otf

  assets:
    - assets/images/
    - assets/file/
    - assets/icons/
    - assets/flags/
    - assets/fonts/
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
